#!/usr/bin/env bash
set -e
cd build
ninja
ninja test
cd ..
./build_self_hosted.sh

echo "Checking wether the llvm ir code of the compiler itself"
echo "generated by bootstrapped compiler is the same as the"
echo "code generated by the self-hosted compiler:"
echo ""

diff ./build/self_hosted.ll ./build/tests/self_combined.ll > /dev/null
if [ $? -eq 0 ]; then
	echo "  WORKS!"
fi

echo ""

echo "Checking wether the self-hosted compiler passes all tests:"
echo ""

./run_all_tests.sh build/self_hosted.elf self

echo "Thanks and see you!"

